name: scrape_server1

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    restart: always
    env_file:
      - .env
    security_opt:
      - no-new-privileges:true
