name: scrape_server

services:
  app:
    container_name: scrape_server
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    restart: always
    init: true
    env_file:
      - .env
    security_opt:
      - no-new-privileges:true
    cpus: 2
    mem_limit: 512m
